import { ImageBackground, StyleSheet, View } from 'react-native';

import CustomButton from 'components/CustomButton';
import Paragraph from 'components/Paragraph';
import Title from 'components/Title';
import { router } from 'expo-router';

const WelcomeScreenStepOne = () => {
  return (
    <ImageBackground source={require('../../assets/step-1.png')} style={styles.background} resizeMode="center">
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Title titleText="Learn Anything With Smart AI Quizzes" extraStyle={{ textAlign: 'center' }} />
          <Paragraph text="Tap into YouTube videos and get quiz questions generated by AI" extraStyle={{ textAlign: 'center' }} />
        </View>
        <View style={styles.buttonContainer}>
          <CustomButton buttonText="Next" buttonType="confirmation" onPress={() => router.push('/on-board/step-2')} />
        </View>
      </View>
    </ImageBackground>
  );
};

const styles = StyleSheet.create({
  background: {
    height: 900,
    flex: 1,
    padding: 20,
    backgroundColor: '#000614',
  },
  container: {
    flex: 1,
    justifyContent: 'space-between',
  },
  textContainer: {
    gap: 12,
  },
  buttonContainer: {
    alignItems: 'center',
  },
});

export default WelcomeScreenStepOne;
