export const colors = {
  correctOrConfirm: '#0CAB5C',
  wrongOrWarning: '#BF2B2B',
  cardBackground: '#1D1D1F',
  activeButtonBackground: '#13AFBE',
  cancelButtonBackground: '#BB3431',
  optionButtonBackground: '#1F2122',
  buttonText: 'white',
  defaultborderButton: '#4D4D4D',
  selectedButtonBorder: '#0DD3D8',
  darkTheme: '#0F1112',
  lightTheme: '#f5f5f5',
  darkButton: '1F2125',
  inputBackground: '#161618',
  placehoolderInputText: '#767678',
  notificationOrPargraph: '#EED34F',
  progressBar: '#3E5BC3',
  // new colors of the new ui
  magicBlue: '#0021C5',
  paper: '#FFFFFF',
};
