import { ImageBackground, View, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { CustomButton } from 'components/CustomButton';
import { Title } from 'components/Title';
import { Paragraph } from 'components/Paragraph';

const WelcomeScreenStepOne = () => {
  const navigation = useNavigation();

  return (
    <ImageBackground source={require('../../assets/step-1.png')} style={styles.background} resizeMode="center">
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Title titleText="Learn Anything With Smart AI Quizzes" extraStyle={{ textAlign: 'center' }} />
          <Paragraph text="Tap into YouTube videos and get quiz questions generated by AI" extraStyle={{ textAlign: 'center' }} />
        </View>
        <View style={styles.buttonContainer}>
          <CustomButton buttonText="Next" buttonType="confirmation" onPress={() => navigation.navigate('step-2')} />
        </View>
      </View>
    </ImageBackground>
  );
};

const styles = StyleSheet.create({
  background: {
    flex: 1,
    paddingTop: 20,
    paddingBottom: 20,
    backgroundColor: '#000614',
  },
  container: {
    flex: 1,
    justifyContent: 'space-between',
  },
  textContainer: {
    gap: 12,
  },
  buttonContainer: {
    alignItems: 'center',
  },
});

export default WelcomeScreenStepOne;
